### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by Sonico98** [volkanturkut/DeltArch#1]
How do you install this? I've downloaded the repo's zip and extracted it in /storage/emulated/0/RetroArch/overlays. Then went into RetroArch, opened any core (i.e. the N64 one), quickmenu, overlays, chose the info.cfg file and when I went back to the game screen, there was no overlay at all.

**Comment by volkanturkut** [comment]
hi this project is not unfinished so N64 is not working so now just GBA and GB-C edge to edge fully working
